Document: libcaenrfid
Title: Debian libcaenrfid Manual
Author: <insert document author here>
Abstract: This manual describes what libcaenrfid is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/libcaenrfid/libcaenrfid.sgml.gz

Format: postscript
Files: /usr/share/doc/libcaenrfid/libcaenrfid.ps.gz

Format: text
Files: /usr/share/doc/libcaenrfid/libcaenrfid.text.gz

Format: HTML
Index: /usr/share/doc/libcaenrfid/html/index.html
Files: /usr/share/doc/libcaenrfid/html/*.html
